name: Build and Preview Site
on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]


jobs:
  triger-previewing-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build ðŸ”§ 
        run: |
          npm install -g gatsby-cli
          npm install
          npm run gatsby build && echo 'User-agent: *\nDisallow: /' > public/robots.txt
      - name: Zip Site
        run: bash ./script.sh

      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: public-dir
          path: ./public-dir.zip
          retention-days: 1
      - name: Triger Inner workflow
        run: echo "trigering inner workflow"
